require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot

# Max line length is changed from default 80
Layout/LineLength:
  Max: 100

# Max class definition is changed from default 100
Metrics/ClassLength:
  Max: 150

# Max module definition is changed from default 100
Metrics/ModuleLength:
  Max: 150

# Exclude block length maximum on specs
Metrics/BlockLength:
  Enabled: false

# Allowed number of let/subject
Naming/VariableNumber:
  Enabled: false

# Class top level documentation
Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always

# Allow to read ENV variable
Rails/EnvironmentVariableAccess:
  AllowReads: true

Rails/SkipsModelValidations:
  Exclude:
    - 'lib/scripts/**/*.rb'

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

Rails/Output:
  Exclude:
    - 'lib/scripts/**/*.rb'
    - 'db/seeds/**/*.rb'
    - 'db/seeds.rb'

# RSpec example length
RSpec/ExampleLength:
  Enabled: false

# Allowed number of let/subject
RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'
